# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PRODUCCION

variables:
- group: credenciales

steps:
- script: |
    rsync -auv -e 'sshpass -p "$(password_produccion)" ssh -o StrictHostKeyChecking=no' --chown=soprolefoodprofe:soprolefoodprofe  --exclude='.htaccess' --exclude='*.md' --exclude='*.yml' --exclude='.git' --exclude='.env'  --exclude='.env.example' --exclude='composer.lock' --exclude='BD' . root@45.33.62.181:/home/soprolefoodprofe/public_html/
  displayName: 'Rsync a servidor de produccion'


- task: SSH@0
  inputs:
    sshEndpoint: 'produccion'
    runOptions: 'commands'
    commands: |
      cd /home/soprolefoodprofe/public_html/ && php artisan migrate --force
    readyTimeout: '20000'
