# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- DESARROLLO

variables:
- group: credenciales

steps:
- script: |
    rsync -auv -e 'sshpass -p "$(password_desarrollo)" ssh -o StrictHostKeyChecking=no' --chown=soprolefoodprofe:soprolefoodprofe  --exclude='.htaccess' --exclude='*.md' --exclude='*.yml' --exclude='.git' --exclude='.env'  --exclude='.env.example' --exclude='composer.lock' --exclude='BD' . root@209.126.108.6:/home/soprolefoodprofe/public_html/
  displayName: 'Rsync a servidor de desarrollo'


- task: SSH@0
  inputs:
    sshEndpoint: 'desarrollo'
    runOptions: 'commands'
    commands: |
      cd /home/soprolefoodprofe/public_html/ && composer update && php artisan migrate
    readyTimeout: '20000'
